### ISSUE TITLE
Casts on the same target, same buff

### ISSUE THREAD

**Issue by MrSanar** [Sentilix/buffalo#1]
Hi,
I play class Prist.
Faled any buff.
Its hapen on WoTLK 3.4.0.46248
Error txt from "Swatter":
<details> 
Date: 2022-10-30 19:05:08
ID: 6
Error occured in: Global
Count: ∞
Message: ..\AddOns\Buffalo\Buffalo.lua line 1191:
   attempt to index local 'parentBuffInfo' (a nil value)
Debug:
   [string "@Buffalo\Buffalo.lua"]:1191:
      Buffalo\Buffalo.lua:902
   [string "@Buffalo\Buffalo.lua"]:2530: Buffalo_OnTimer()
   [string "*:OnUpdate"]:2:
      [string "*:OnUpdate"]:1
Locals:
debug = nil
roster = <table> {
 player = <table> {
 }
 party3 = <table> {
 }
 party1 = <table> {
 }
 party4 = <table> {
 }
 party2 = <table> {
 }
}
startNum = 0
endNum = 4
groupType = nil
unitid = "party4"
groupCount = 1
playername = "Санар"
currentUnitid = "player"
currentTime = 1353310.603000
assignedGroups = <table> {
 1 = 3
 2 = 3
 3 = 3
 4 = 3
 5 = 3
 6 = 3
 7 = 3
 8 = 3
}
binValue = nil
unitname = "Гэхеджи-Пламегор"
MissingBuffs = <table> {
 1 = <table> {
 }
}
missingBuffIndex = 2
castingPlayerAndRealm = "Санар-Пламегор"
(for index) = 1
(for limit) = 1
(for step) = 1
groupIndex = 1
groupMask = 3
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 Защита от темной магии = <table> {
 }
 Божественный дух = <table> {
 }
 Внутренний огонь = <table> {
 }
 Слово силы: Стойкость = <table> {
 }
}
(for control) = "Слово силы: Стойкость"
buffName = "Слово силы: Стойкость"
buffInfo = <table> {
 PARENT = "Молитва стойкости"
 PRIORITY = 53
 CLASSES = 1023
 GROUP = false
 SPELLID = 2791
 ICONID = 135987
 BITMASK = 1
}
buffMissingCounter = 3
groupMemberCounter = 5
MissingBuffsInGroup = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
}
parentBuffInfo = nil
bufferUnitid = "player"
(*temporary) = 4
(*temporary) = 1
(*temporary) = 4
(*temporary) = <table> {
 BuffMask = 3
 IsOnline = 1
 Group = 1
 Class = "HUNTER"
 IsDead = false
 ClassMask = 2
}
(*temporary) = 7
(*temporary) = 1
(*temporary) = 3
(*temporary) = 1
(*temporary) = 1
(*temporary) = "Пламегор"
(*temporary) = "Пламегор"
(*temporary) = " "
(*temporary) = nil
(*temporary) = "attempt to index local 'parentBuffInfo' (a nil value)"
DEBUG_FunctionList = <table> {
}
IsBuffer = true
Buffalo_InitializationComplete = true
BUFFALO_ICON_COMBAT = "Interface\Icons\Ability_dualwield"
BUFFALO_ICON_PLAYERDEAD = "Interface\Icons\Ability_rogue_feigndeath"
Buffalo_PlayerClass = "PRIEST"
CLASS_MASK_ALL = 1023
CLASS_MATRIX = <table> {
 DEATHKNIGHT = <table> {
 }
 WARRIOR = <table> {
 }
 PALADIN = <table> {
 }
 MAGE = <table> {
 }
 PRIEST = <table> {
 }
 WARLOCK = <table> {
 }
 ROGUE = <table> {
 }
 DRUID = <table> {
 }
 SHAMAN = <table> {
 }
 HUNTER = <table> {
 }
}
CONFIG_AssignedBuffGroups = <table> {
 1 = 3
 2 = 3
 3 = 3
 4 = 3
 5 = 3
 6 = 3
 7 = 3
 8 = 3
}
Buffalo_CurrentRaidMode = 1
BUFFALO_RAIDMODE_PERSONAL = 1
CONFIG_AssignedRaidGroups = <table> {
}
CONFIG_AssignedBuffSelf = 263
BUFF_MATRIX = <table> {
 Защита от темной магии = <table> {
 }
 Божественный дух = <table> {
 }
 Внутренний огонь = <table> {
 }
 Слово силы: Стойкость = <table> {
 }
}
CONFIG_RenewOverlap = 100
A = <table> {
 chatColorHot = "|c80F8F8F8"
 chatColorNormal = "|c80E0C020"
 addonVersion = "0.5.2"
 addonShortName = "BUFFALO"
 isDebugBuild = false
 addonExpansionLevel = 3
 addonPrefix = "BuffaloV1"
 addonName = "Buffalo"
 buildVersion = 4
 chatChannels = <table> {
 }
 addonAuthor = "Mimma @ <EU-Pyrewood Village>"
}
CONFIG_AssignedClasses = <table> {
 DEATHKNIGHT = 5
 WARRIOR = 5
 PALADIN = 7
 MAGE = 7
 PRIEST = 7
 WARLOCK = 7
 HUNTER = 7
 DRUID = 7
 SHAMAN = 7
 ROGUE = 5
}
CONFIG_GroupBuffThreshold = 3
CONFIG_PlayerBuffPriority = 90
CONFIG_AnnounceMissingBuff = false
lastBuffTarget = ""
lastBuffStatus = ""
BUFFALO_COLOUR_EXPIRING = "|c80F0F000"
BUFFALO_COLOUR_MISSING = "|c80F05000"

AddOns:
  Swatter, v3.4.6817 (SwimmingSeadragon)
  alaTradeSkill, v304r.221018
  AlreadyKnown, v1.47
  Auctionator, v10.0.3
  BagBrother, v
  BagFreeSpaceCounter, v1.0.4
  Bagnon, v10.0.3
  BeanCounter, v3.4.6811 (SwimmingSeadragon)
  Buffalo, v0.5.2
  BuffOverlay, vv12.0.3
  BuffTimers, vv1.7.0
  ChatCopyPaste, v1.13
  ChatLinkIcons, v2.13
  Comix, v9.2.7.0
  DeathNote, v30400.5-release
  Details, v#Details.DF.Wrath.10205.146
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  DisenchantCraftedItems, v2.1.3
  DoomCooldownPulse, v
  Enchantrix, v3.4.6821 (SwimmingSeadragon)
  EnchantrixBarker, v3.4.6813 (SwimmingSeadragon)
  EnchantVellum, v1.3.2
  ErrorMonster, vv10.0.0
  FarmingBar, vv3.6.7
  GatherMate2, v1.46.3-classic
  HealBot, v3.4.0.16
  HealBotData, v
  HealBotOptions, v
  HealBotTips, v
  Mapster, v1.10.0
  MinimapButtonButton, v1.8.6
  MoveAny, v0.7.17
  NameplateCooldowns, v30400.3-release
  NoteworthyII, v2.4.0
  Peddler, v
  Quartz, v3.7.0
  Questie, v7.4.2
  SexyMap, vv10.0.3
  SlideBar, v3.4.6815 (SwimmingSeadragon)
  Stubby, v3.4.6816 (SwimmingSeadragon)
  WhispList, v4.10
  BlizRuntimeLib_ruRU v3.4.0.30400 <none>
  (ck=4b7)
</details>

**Comment by Sentilix** [comment]
Hi,

The problem has been resolved in release 0.5.3, turns out that when a character does not have a group buff learned the addon fails, and keep on failing on every scan. Let me hear if there are still problems after updating.

Thanks for the report.

**Comment by MrSanar** [comment]
Big, thx.
